-- MySQL Script generated by MySQL Workbench
-- qui 06 set 2018 10:10:35 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema avalon
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `avalon` ;

-- -----------------------------------------------------
-- Schema avalon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `avalon` DEFAULT CHARACTER SET utf8 ;
USE `avalon` ;

-- -----------------------------------------------------
-- Table `avalon`.`avalon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avalon`.`avalon` ;

CREATE TABLE IF NOT EXISTS `avalon`.`avalon` (
  `id` INT(13) NOT NULL DEFAULT '1',
  `players` VARCHAR(400) NULL DEFAULT NULL,
  `cards` VARCHAR(400) NULL DEFAULT NULL,
  `total` INT NULL,
  `result` VARCHAR(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `avalon`.`card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avalon`.`card` ;

CREATE TABLE IF NOT EXISTS `avalon`.`card` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(400) NOT NULL,
  `team` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `avalon`.`player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avalon`.`player` ;

CREATE TABLE IF NOT EXISTS `avalon`.`player` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `avalon`.`mission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avalon`.`mission` ;

CREATE TABLE IF NOT EXISTS `avalon`.`mission` (
  `id` INT NOT NULL,
  `players` VARCHAR(400) NULL,
  `cards` VARCHAR(400) NULL,
  `result` VARCHAR(400) NULL,
  `success` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
